export const GET_SORTBY = 'GET_SORTBY';
export const GET_SEARCHBY = 'GET_SEARCHBY';
export const GET_HOTMOVIE = 'GET_HOTMOVIE';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_SAMEGENRE = 'GET_SAMEGENRE';
export const GET_PAGE_PARAMS = 'GET_PAGE_PARAMS';
export const GET_PAGE_PARAMS_DEFAULT = 'GET_PAGE_PARAMS_DEFAULT';

