// eslint-disable-next-line no-unused-vars
const mockedData = {
    status: 'ok',
    totalResults: 4387,
    articles: [
        {
            source: {
                id: null,
                name: 'Fxstreet.com',
            },
            author: 'FXStreet Team',
            title: 'Cryptocurrencies News: Tron must defend falling channel, Bitcoin Loses $8,000 Support',
            description: 'Bitcoin Price Loses $8,000 Support Bitcoin (BTC) fell below $8,000 on Nov. 21, after several days of downward price pressure finally cost the cryptocurrency',
            url: 'https://www.fxstreet.com/news/cryptocurrencies-news-tron-must-defend-falling-channel-bitcoin-loses-8-000-support-201911211503',
            urlToImage: 'https://editorial.fxstreet.com/images/Markets/Currencies/Cryptocurrencies/cryptos_Large.jpg',
            publishedAt: '2019-11-21T15:03:30Z',
            content: 'Tron is disintegrating within a falling wedge pattern. The declines come after a failed attempt to rise above the resistance at $0.023. A lower high and lower low pattern has been the norm in the last three weeks. Possible support areas have been shuttered to… [+1377 chars]',
        },
        {
            source: {
                id: null,
                name: 'Zerohedge.com',
            },
            author: 'Tyler Durden',
            title: 'Bitcoin Busts Below $8,000 To One-Month Lows',
            description: "Bitcoin Busts Below $8,000 To One-Month Lows Another sea of red across cryptos this morning after tumbling in early European trading (it's been an ugly 7 days as the image below shows)... Source: Coin360 Bitcoin Cash is leading the decline on the week along w…",
            url: 'https://www.zerohedge.com/crypto/bitcoin-busts-below-8000-one-month-lows',
            urlToImage: 'https://zh-prod-1cc738ca-7d3b-4a72-b792-20bd8d8fa069.storage.googleapis.com/s3fs-public/styles/max_650x650/public/2019-11/2019-11-21_6-28-26.jpg?itok=dQyGVrTh',
            publishedAt: '2019-11-21T14:50:37Z',
            content: "Another sea of red across cryptos this morning after tumbling in early European trading (it's been an ugly 7 days as the image below shows)...\r\nSource: Coin360\r\nBitcoin Cash is leading the decline on the week along with Litecoin...\r\nSource: Bloomberg\r\nBut Bic… [+1249 chars]",
        },
        {
            source: {
                id: null,
                name: 'Cointelegraph.com',
            },
            author: 'Cointelegraph By Will Heasman',
            title: 'Google, Facebook Take on Banking Duties, Crypto Shrugged to the Side?',
            description: 'With major tech firms shifting their focus to finance, what does this mean for the future of crypto and the wider financial system?',
            url: 'https://cointelegraph.com/news/google-facebook-take-on-banking-duties-crypto-shrugged-to-the-side',
            urlToImage: 'https://images.cointelegraph.com/images/740_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy81Y2I1NzZmMjgyM2YxYzM4OTVkMDYzMDE5NmJhOTdjMi5qcGc=.jpg',
            publishedAt: '2019-11-21T14:45:00Z',
            content: 'A peculiar phenomenon is occurring within the economic sector. In fact, it’s been transpiring over the past few decades. After the rise of the internet and the development of effective communications, the financial industry underwent a technical reconstructio… [+9791 chars]',
        },
        {
            source: {
                id: null,
                name: 'Govtech.com',
            },
            author: null,
            title: 'Texas School District Pays Ransom to Regain Access to Files',
            description: '(TNS) Port Neches-Groves ISD in the Beaumont, Texas, area paid an undisclosed amount of money via Bitcoin to a suspected overseas cyberattacker who encrypted millions of the district’s files and issued a four-day deadline to respond to the criminal demands. B…',
            url: 'https://www.govtech.com/security/Texas-School-District-Pays-Ransom-to-Regain-Access-to-Files.html',
            urlToImage: 'https://media.governing.com/images/shutterstock_411146515.jpg',
            publishedAt: '2019-11-21T14:41:00Z',
            content: '(TNS) — Port Neches-Groves ISD in the Beaumont, Texas, area paid an undisclosed amount of money via Bitcoin to a suspected overseas cyberattacker who encrypted millions of the district’s files and issued a four-day deadline to respond to the criminal demands.… [+4362 chars]',
        },
        {
            source: {
                id: null,
                name: 'Finextra.com',
            },
            author: 'Editorial Team',
            title: 'How Cryptocurrencies Can Help Global Economy and Build a Better Future (Pooja K)',
            description: 'Cryptocurrencies have long been discussed and debated, but they’re only now coming to light as finan...',
            url: 'https://www.finextra.com/blogposting/18159/how-cryptocurrencies-can-help-global-economy-and-build-a-better-future?utm_medium=rssfinextra&utm_source=finextrablogs',
            urlToImage: 'https://www.finextra.com/finextra-images/member_photos/thumb_109495_pooja_k.png',
            publishedAt: '2019-11-21T14:38:55Z',
            content: 'Cryptocurrencies have long been discussed and debated, but theyre only now coming to light as financial tools that can be accessible and useful to more than only die-hard connoisseurs. Cryptocurrencies have the potential to enable social and economic growth\r\n… [+4882 chars]',
        },
        {
            source: {
                id: null,
                name: 'Finextra.com',
            },
            author: 'Editorial Team',
            title: 'How Cryptocurrencies Can Help Global Economy and Build a Better Future',
            description: 'Cryptocurrencies have long been discussed and debated, but they’re only now coming to light as finan...',
            url: 'https://www.finextra.com/blogposting/18159/how-cryptocurrencies-can-help-global-economy-and-build-a-better-future?utm_medium=rssfinextra&utm_source=finextrafeed',
            urlToImage: 'https://www.finextra.com/finextra-images/member_photos/thumb_109495_pooja_k.png',
            publishedAt: '2019-11-21T14:38:55Z',
            content: 'Cryptocurrencies have long been discussed and debated, but theyre only now coming to light as financial tools that can be accessible and useful to more than only die-hard connoisseurs. Cryptocurrencies have the potential to enable social and economic growth\r\n… [+4882 chars]',
        },
        {
            source: {
                id: null,
                name: 'Dailyfx.com',
            },
            author: 'Ben Lobel, Martin Essex, MSTA',
            title: 'Traders Debate: US-China Trade War, Forex Forecasts &amp; More | Podcast',
            description: 'Learn about the US-China Trade War, forex forecasts and more with DailyFX analysts Nicholas Cawley and David Cottle.',
            url: 'https://www.dailyfx.com/forex/education/trading_tips/post_of_the_day/2019/11/21/traders-debate-us-china-trade-war.html',
            urlToImage: 'https://a.c-dn.net/b/1ecZtj/headline_shutterstock_132729920_(1).jpg',
            publishedAt: '2019-11-21T14:18:00Z',
            content: 'Talking points on this podcast: \r\n<ul><li>US/China trade war: What now for EUR/USD?</li><li>GBP/USDs future as the Brexit dialogue continues</li><li>Is Bitcoin finally maturing as a market?</li></ul>This time on Trading Global Markets Decoded, our host Martin… [+2372 chars]',
        },
        {
            source: {
                id: 'google-news',
                name: 'Google News',
            },
            author: null,
            title: 'NordVPN 5.1.4 - Military-grade protection online. (Shareware)',
            description: 'NordVPN gives you military-grade protection online, and you can access all your favorite sites without restriction. We never log your activity when using our servers, which are operated under the jurisdiction of Panama, where there are no mandatory data reten…',
            url: 'http://feedproxy.google.com/~r/macupdate/~3/f7rvrmzl84Y/1574345102',
            urlToImage: null,
            publishedAt: '2019-11-21T14:05:02Z',
            content: null,
        },
        {
            source: {
                id: null,
                name: 'Dailydot.com',
            },
            author: 'Ken Griggs',
            title: 'Smoke ’em, pass ’em Week 12: I quit',
            description: 'OK fantasy football advice for the lonely. The post Smoke ’em, pass ’em Week 12: I quit appeared first on The Daily Dot.',
            url: 'https://www.dailydot.com/upstream/start-em-sit-em-week-12-fantasy-football/',
            urlToImage: 'https://www.dailydot.com/wp-content/uploads/2019/11/start_em_sit_em_week_12.png',
            publishedAt: '2019-11-21T14:02:28Z',
            content: 'Start em, sit em, and other fantasy football advice.\r\nIts Week 12 and Ive decided to quit fantasy football for good. Its over this time. I cant take it any longer. How long can I care about something that doesnt matter? Teams whimsically trading out running b… [+7920 chars]',
        },
        {
            source: {
                id: null,
                name: 'Siliconangle.com',
            },
            author: 'Kyt Dotson',
            title: 'Ubisoft joins Ultra’s blockchain testnet as an infrastructure partner and block producer',
            description: 'Next-generation games distribution platform Ultra announced today that Ubisoft Inc., the big developer, publisher and distributor of video games, will become the first major gaming company to join its blockchain distributed ledger. Ubisoft it doing so as a co…',
            url: 'https://siliconangle.com/2019/11/21/ubisoft-joins-ultras-blockchain-testnet-infrastructure-partner-block-producer/',
            urlToImage: 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2019/11/ultra-logo.jpg',
            publishedAt: '2019-11-21T14:02:00Z',
            content: 'Next-generation games distribution platform Ultra announced today that Ubisoft Inc., the big developer, publisher and distributor of video games, will become the first major gaming company to join its blockchain distributed ledger.\r\nUbisoft it doing so as a c… [+5753 chars]',
        },
        {
            source: {
                id: null,
                name: 'Lowendbox.com',
            },
            author: 'Frank Williams',
            title: 'SupremeVPS – SSD Linux VPS Plans starting at $42.50 a year!!!',
            description: 'SupremeVPS is back with some exclusive offers for the community. This time, they are focusing on their SSD Linux VPS offers. As always, every offer by SupremeVPS is all powered by RAID-10 SSD’s for top notch performance! Our platform provides you with maximum…',
            url: 'https://lowendbox.com/blog/supremevps-ssd-linux-vps-plans-starting-at-42-50-a-year/',
            urlToImage: 'http://lowendbox.com/wp-content/uploads/2018/07/supremevps-118x300.jpg',
            publishedAt: '2019-11-21T14:00:58Z',
            content: 'SupremeVPS is back with some exclusive offers for the community. This time, they are focusing on their SSD Linux VPS offers.As always, every offer by SupremeVPS is all powered by RAID-10 SSD’s for top notch performance!Our platform provides you with maximum p… [+2540 chars]',
        },
        {
            source: {
                id: null,
                name: 'Venturebeat.com',
            },
            author: 'Dean Takahashi',
            title: 'Ubisoft helps Ultra validate transactions on its blockchain for gamers',
            description: 'is announcing that French video game giant Ubisoft will help validate transactions on its blockchain for gamers.',
            url: 'https://venturebeat.com/2019/11/21/ubisoft-helps-ultra-validate-transactions-on-its-blockchain-for-gamers/',
            urlToImage: 'https://venturebeat.com/wp-content/uploads/2018/05/ultra-3.jpg?w=1200&strip=all',
            publishedAt: '2019-11-21T14:00:25Z',
            content: 'Ultra is one of a number of companies that believes blockchain and cryptocurrency can make the distribution of games more efficient and gamers more loyal. And today, the Paris company is announcing that French video game giant Ubisoft will help validate trans… [+2666 chars]',
        },
        {
            source: {
                id: null,
                name: 'Rlslog.net',
            },
            author: 'TheInsertus',
            title: 'Bitcoin and Lightning Network on Raspberry Pi-P2P',
            description: 'Compile and run Bitcoin full nodes, lightning nodes, and user-friendly web-apps that help abstract the complexities of Bitcoin. This book not only explains the tools and techniques to help readers build their own banks and banking apps, but it also tells a st…',
            url: 'http://www.rlslog.net/bitcoin-and-lightning-network-on-raspberry-pi-p2p/',
            urlToImage: null,
            publishedAt: '2019-11-21T13:53:33Z',
            content: 'Compile and run Bitcoin full nodes, lightning nodes, and user-friendly web-apps that help abstract the complexities of Bitcoin. This book not only explains the tools and techniques to help readers build their own banks and banking apps, but it also tells a st… [+1590 chars]',
        },
        {
            source: {
                id: 'crypto-coins-news',
                name: 'Crypto Coins News',
            },
            author: 'Kiril Nikolaev',
            title: 'Biggest Bull Is Preparing for Bitcoin to Skyrocket Despite Recent Crash',
            description: 'Bitcoin’s price action has been bearish as of late. Nevertheless, the biggest… The post Biggest Bull Is Preparing for Bitcoin to Skyrocket Despite Recent Crash appeared first on CCN.com',
            url: 'https://www.ccn.com/biggest-bull-bitcoin-skyrocket-despite-recent-crash/',
            urlToImage: 'https://www.ccn.com/wp-content/uploads/2019/11/shutterstock_757373461-scaled.jpg',
            publishedAt: '2019-11-21T13:50:27Z',
            content: '<ul><li>Bitcoins price action has been bearish as of late.</li><li>Nevertheless, the biggest bull in Crypto Twitter sees a reversal in the horizon.</li><li>Other traders do not share an optimistic outlook and bet on a bitcoin plummet to $6,000 levels.</li></u… [+3598 chars]',
        },
        {
            source: {
                id: null,
                name: 'Prnewswire.com',
            },
            author: null,
            title: "Digital Wealth Media Inc. Unveils New Will Developed Specifically for the 'Digital Age'",
            description: "MONTREAL, Nov. 21, 2019 /PRNewswire/ -- Digital Wealth Media Inc. announces the launch of a new digital will that allows users to protect their digital assets without hiring an expensive attorney. \"Twenty years ago, a product like this wasn't necessary, but n…",
            url: 'https://www.prnewswire.com/news-releases/digital-wealth-media-inc-unveils-new-will-developed-specifically-for-the-digital-age-300962830.html',
            urlToImage: 'https://mma.prnewswire.com/media/1032972/Digital_Wealth_Media_Inc_digital_will.jpg?p=facebook',
            publishedAt: '2019-11-21T13:48:00Z',
            content: "MONTREAL, Nov. 21, 2019 /PRNewswire/ -- Digital Wealth Media Inc. announces the launch of a new digital will that allows users to protect their digital assets without hiring an expensive attorney.\r\n\"Twenty years ago, a product like this wasn't necessary, but … [+2673 chars]",
        },
        {
            source: {
                id: null,
                name: 'Theconversation.com',
            },
            author: 'Gavin Brown, Senior Lecturer, Finance, Manchester Metropolitan University, Richard Whittle, Research Fellow in Economics, Manchester Metropolitan University',
            title: "More than 1,000 cryptocurrencies have already failed – here's what will affect successes in future",
            description: 'With Wall Street slowly taking charge of crypto, the days of radical outsiders launching successful altcoins may be numbered.',
            url: 'http://theconversation.com/more-than-1-000-cryptocurrencies-have-already-failed-heres-what-will-affect-successes-in-future-127463',
            urlToImage: 'https://images.theconversation.com/files/302732/original/file-20191120-524-1njq9ry.jpg?ixlib=rb-1.1.0&rect=115%2C469%2C5139%2C2569&q=45&auto=format&w=1356&h=668&fit=crop',
            publishedAt: '2019-11-21T13:47:23Z',
            content: 'Gaining currency? Wit Olszewski Many cryptocurrencies have been launched in the past few years, often to great fanfare and celebration, only to fade and fail as the public and investors shun them. According to Coinopsy, which tracks such failures, there are s… [+6714 chars]',
        },
        {
            source: {
                id: 'cnbc',
                name: 'CNBC',
            },
            author: 'CNBC US Source',
            title: 'Your first trade for Thursday, Nov. 21',
            description: 'The "Fast Money" traders share their first moves for the market open.',
            url: 'https://www.cnbc.com/2019/11/21/your-first-trade-for-thursday-nov-21.html',
            urlToImage: 'https://image.cnbcfm.com/api/v1/image/104245575-final-trade-logo.jpg?v=1485535955',
            publishedAt: '2019-11-21T13:47:00Z',
            content: 'The "Fast Money" traders shared their first moves for the market open.\r\nPete Najarian was a buyer of Restoration Hardware.\r\nMark Tepper was a buyer of Salesforce.\r\nGuy Adami was a buyer of Quest Diagnostics.\r\nKaren Finerman was a buyer of Home Depot.\r\nDisclos… [+1216 chars]',
        },
        {
            source: {
                id: null,
                name: 'Newsbtc.com',
            },
            author: 'Aayush Jindal',
            title: 'Bitcoin (BTC) Price Diving, Gates To $7,400 Now Wide Open',
            description: 'Bitcoin price is diving and it recently broke the $8,000 support area against the US Dollar. The price is under a lot of pressure and recently traded to a new monthly low at $7,828. Morning’s bearish flag pattern was breached with support near $8,080 on the h…',
            url: 'https://www.newsbtc.com/2019/11/21/bitcoin-btc-price-diving-gates-to-7400-now-wide-open/',
            urlToImage: 'https://www.newsbtc.com/wp-content/uploads/2019/08/bitcoin-price-btcanalysis-drop-1200x780.jpg',
            publishedAt: '2019-11-21T13:12:17Z',
            content: '<ul><li>Bitcoin price is diving and it recently broke the $8,000 support area against the US Dollar.</li><li>The price is under a lot of pressure and recently traded to a new monthly low at $7,828.</li><li>Mornings bearish flag pattern was breached with suppo… [+2436 chars]',
        },
        {
            source: {
                id: null,
                name: 'Pymnts.com',
            },
            author: 'PYMNTS',
            title: '$400M Of XRP Tokens Linked To Cybercrime',
            description: 'Cryptocurrency forensics and analysis firm Elliptic found that roughly $400 million worth of XRP tokens on the Ripple payment network is connected to illegal transactions, on Wednesday (Nov. 20). press release The London-based startup said the illicit activit…',
            url: 'https://www.pymnts.com/cryptocurrency/2019/400m-of-ripple-xrp-tokens-linked-to-cybercrime/',
            urlToImage: 'https://securecdn.pymnts.com/wp-content/uploads/2019/11/Elliptic-XRP-Ripple-cryptocurrency-blockchain-dark-web-ponzi-schemes-illegal-transactions-news-457x299.jpg',
            publishedAt: '2019-11-21T13:03:00Z',
            content: 'Cryptocurrency forensics and analysis firm Elliptic found that roughly $400 million worth of XRP tokens on the Ripple payment network is connected to illegal transactions, Elliptic said in a press release on Wednesday (Nov. 20).\r\nThe London-based startup said… [+1984 chars]',
        },
        {
            source: {
                id: null,
                name: 'Forbes.com',
            },
            author: 'Greg Herlean, CommunityVoice, Greg Herlean, CommunityVoice https://www.forbes.com/sites/forbesfinancecouncil/people/gregherlean/',
            title: 'Bitcoin Versus Real Estate: Which Investment Is Better For You?',
            description: 'Two popular investment avenues, real estate and bitcoin, have been making waves in today’s market.',
            url: 'https://www.forbes.com/sites/forbesfinancecouncil/2019/11/21/bitcoin-versus-real-estate-which-investment-is-better-for-you/',
            urlToImage: 'https://thumbor.forbes.com/thumbor/600x315/https%3A%2F%2Fblogs-images.forbes.com%2Fforbesfinancecouncil%2Ffiles%2F2019%2F11%2Fa-23-500x500.jpg',
            publishedAt: '2019-11-21T13:00:00Z',
            content: '<ul><li>Share to facebook</li><li>Share to twitter</li><li>Share to linkedin</li></ul>\r\nTwo popular investment avenues, real estate and bitcoin, have been making waves in todays market. When it comes to these opportunities, it can be difficult to discern whic… [+8644 chars]',
        },
    ],
};

module.exports = mockedData;
